---
# install golangci by (go 1.16+):
# go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 10m
  modules-download-mode: mod
  tests: false

  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - bin
    - build
    - dist
    - scripts

# output configuration options
output:
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

# all available settings of specific linters
linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true

  govet:
    # report about shadowed variables
    check-shadowing: false

  gofmt:
    simplify: true

  gocritic:
    disabled-checks:
      - commentFormatting
      - deprecatedComment

  nestif:
    # minimal complexity of if statements to report, 5 by default
    min-complexity: 4

  staticcheck:
    go: "1.18"
    checks: ["all"]

issues:
  exclude:
    - ifElseChain
    - singleCaseSwitch
    - assignOp
    - unlambda

linters:
  disable-all: true
  enable:
    - goimports
    - gocritic
    - misspell
    - govet
    - deadcode
    - varcheck
    - ineffassign
    - structcheck
    - unconvert
    - gofmt
    - gosimple
    - depguard
    - staticcheck
    - errcheck
    - nestif
    - revive
    - lll
  fast: false
